---
all:
  vars:
    ansible_user: ansible
    ansible_python_interpreter: /usr/bin/python3
  children:
    ppi_lab:
      children:
        sensor:
          hosts:
            ppi-sensor:
              ansible_host: 10.10.10.20
        servidores:
          hosts:
            ppi-server:
              ansible_host: 10.10.10.30
        atacantes:
          hosts:
            ppi-kali:
              ansible_host: 10.10.10.40
        clientes_linux:
          hosts:
            ppi-client:
              ansible_host: 10.10.10.50

