interface=ens38
listen-address=10.30.0.10
bind-interfaces
no-resolv
domain-needed
bogus-priv
local=/ppi.lab/
address=/server.ppi.lab/10.30.0.10
address=/web.ppi.lab/10.30.0.10
address=/iperf.ppi.lab/10.30.0.10
log-queries=extra
log-facility=/var/log/dnsmasq-ppi.log
