log_format ppi_json escape=json
  '{"timestamp":"$time_iso8601","remote_addr":"$remote_addr",'
  '"request":"$request","method":"$request_method","uri":"$request_uri",'
  '"status":$status,"bytes_sent":$bytes_sent,"request_time":$request_time,'
  '"referer":"$http_referer","user_agent":"$http_user_agent"}';

limit_conn_zone $binary_remote_addr zone=ppi_conn:10m;
limit_req_zone $binary_remote_addr zone=ppi_req:10m rate=20r/s;

server {
    listen 10.30.0.10:80;
    listen 10.30.0.11:80;
    listen 10.30.0.12:80;
    server_name server.ppi.lab web.ppi.lab web-a.ppi.lab web-b.ppi.lab;
    root /srv/ppi;
    limit_conn ppi_conn 20;
    limit_conn_status 429;
    limit_req zone=ppi_req burst=40 nodelay;
    limit_req_status 429;

    access_log /var/log/nginx/ppi-access.json ppi_json;
    error_log /var/log/nginx/ppi-error.log warn;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok","service":"ppi-web"}\n';
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8090;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
    }

    location /files/ {
        types { application/octet-stream bin; }
        default_type application/octet-stream;
        gzip off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 10.30.0.10:443 ssl;
    server_name server.ppi.lab web.ppi.lab;
    root /srv/ppi;
    limit_conn ppi_conn 20;
    limit_conn_status 429;
    limit_req zone=ppi_req burst=40 nodelay;
    limit_req_status 429;

    ssl_certificate /etc/ssl/certs/ppi-lab.crt;
    ssl_certificate_key /etc/ssl/private/ppi-lab.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/ppi-tls-access.json ppi_json;
    error_log /var/log/nginx/ppi-tls-error.log warn;

    location = /health {
        default_type application/json;
        return 200 '{"status":"ok","service":"ppi-web-tls"}\n';
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8090;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
    }

    location /files/ {
        types { application/octet-stream bin; }
        default_type application/octet-stream;
        gzip off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
